[package]
name = "ferrum"
version = "0.1.0"
edition = "2024"

[dependencies]
magnetite = {path = "../magnetite"}
copper = {path = "../copper"}
softbuffer = "=0.4.6"
winit = "0.30.12"
ab_glyph = "0.2.31"
